### ISSUE TITLE
Create Private Registry How-To Guide

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#164]
Create a guide that outlines how to deploy a private registry on Kubernikus (in CCloud). 

Featuring:

1. Deployment Spec
2. Swift Backend via https://github.com/docker/distribution/pull/2441
3. Expose service via Load Balancer
4. Attach Floating-IP
5. DNS Name
6. SSL Certificate

**Comment by jonathanschwarze** [comment]
I tried different approaches:

**#1 Private Registry Add-on by Kubernetes** (https://github.com/kubernetes/kubernetes/tree/release-1.7/cluster/addons/registry)

There was an addon for private docker registries available. Unfortunately this doesn’t work with Kubernetes > 1.7. The idea was to run a registry in a pod on a node and proxies on all nodes exposing a port to this node via hostPort. Docker sees the registry as localhost therefore no issues with the docker insecure registry policy. 

But it doesn’t work anymore, I ran into issues with the proxies like this:
https://github.com/kubernetes/kubernetes/issues/43986

I couldn’t figure out why they decided to bury this feature. Just some old related issues 

https://github.com/kubernetes/kubernetes/issues/1319
https://github.com/kubernetes/kubernetes/issues/19033

**#2 Helm Docker Registry** (https://github.com/kubernetes/charts/tree/master/stable/docker-registry)

The chart doesn’t work too. 
https://github.com/kubernetes/charts/issues/2991

**#3 Manual installing registry on node**

Another solutions is deploying a registry on a node manually. SSH, tls certs creation, dns etc. Not sure if we should propose this since it could lead to other issues. 

https://docs.docker.com/registry/deploying/#run-an-externally-accessible-registry
