### ISSUE TITLE
Migrate to FilteredSharedInformer

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#169]
With `client-go` v6.0.0 there's now a `FilteredSharedInformer` that can be scoped to a namespace. This allows us to refactor our own custom filter. There's then also potential for simplifying the controller initialisation. 

As seen here: https://github.com/sapcc/kubernikus/blob/master/pkg/controller/operator.go#L216-L246

Production Example:
https://github.com/jetstack/cert-manager/blob/b978faa28c9f0fb0414b5d7293fab7bde65bde76/cmd/controller/app/controller.go#L123

See also: http://blog.kubernetes.io/2018/01/introducing-client-go-version-6.html

**Comment by databus23** [comment]
I started looking at this on friday. Its nice for the kubernikus CRD but its not working for our `Podnformer` because there way have a custom (index)[https://github.com/sapcc/kubernikus/blob/master/pkg/controller/operator.go#L243].

I'm starting to think that maybe instead of struggling with the `factories` maybe we should just store and share the Informers directly. I might be missing something but I don't see much benefit in using these factories.
