### ISSUE TITLE
Switch Etcd Volume AccessMode

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#71]
Cinder: ReadWriteOnce
NFS: ReadWriteMany

We default to `ReadWriteMany` which doesn't work in Cinder.

**Comment by databus23** [comment]
The problem here is we need both. For installing klusters in the barematel admin cluster.
As the is specific to the parent kubernetes cluster hosting the kibe-master chart this should be command line flag or we need to autodetect this somehow. Looking at the storages classes maybe?
In the admin cluster we have none atm.
I would like `ReadWriteOnce` by the default as this is the common one and only switch to `ReadWriteMany` if we know we are in a barematel cluster that has nfs volumes.
Any ideas?

**Comment by databus23** [comment]
So here is my suggestion:
* The default will be `ReadWriteOnce`
* The operator will overwrite that only if no storage class of type cinder is found AND there is at least one `pv` with accesmode `ReadWriteMany`

SGTY @BugRoger ?

**Comment by BugRoger** [comment]
Sounds good
