### ISSUE TITLE
Default Security Group Missing on Nodes

### ISSUE THREAD

**Issue by BugRoger** [sapcc/kubernikus#78]
New nodes are (sometimes) missing the default security group. 

Looks like gophercloud only supports referencing the security group by name. Reverse engineering of Elektra instance creations showed, that Elektra is sending a UUID instead of `default`.

We can try to find out why the security group is missing in some cases. Or just fetch the UUID as Elektra does and try to cram it through gophercloud somehow.

**Comment by BugRoger** [comment]
+1

**Comment by BugRoger** [comment]
Fixed by 95894a14601e546a78d1a28b5206d6daa309c94d

**Comment by databus23** [comment]
Two things on my mind.

1. We should try to reproduce this with a simple curl command posting to `/severs/create`

2. If it really is caused by using the security group name instead of the id we can easily change gophercloud to do so by wrapping providing our own implementation of[CreateOptsBuilder](https://github.com/gophercloud/gophercloud/blob/92fb632e86f730790c3d240e468617c6f8d4a3bf/openstack/compute/v2/servers/requests.go#L83) wrapping the [CreateOpts](https://github.com/gophercloud/gophercloud/blob/92fb632e86f730790c3d240e468617c6f8d4a3bf/openstack/compute/v2/servers/requests.go#L130) struct.

@BugRoger Can you caugh up the full request payload for a server create so that we can try this a few times using curl?

**Comment by BugRoger** [comment]
I just saw Nodes without SecurityGroup again... ><

![image](https://user-images.githubusercontent.com/147369/34297629-88ba308e-e719-11e7-9f1f-3a04ab5be128.png)

This is running the latest operator. I double checked...

**Comment by databus23** [comment]
Merry Christmas!🎁 💩

**Comment by BugRoger** [comment]
Gone for good (famous last words).
